// Generated by CoffeeScript 1.6.2
(function() {
  angular.module('myApp.filters', []).filter('appendHey', [
    function() {
      return function(text) {
        return text + '  heyy';
      };
    }
  ]);

}).call(this);
